### ISSUE TITLE
Replication policy cross multiple cities with one special deferred?

### ISSUE THREAD

**Issue by xuning97** [facebookincubator/LogDevice#203]
Hi, I want to utilize LogDevice's cross DC support, for example, I have five DCs, A, B, C, D, F. and A/B are in the same city, C/D in another nearby city. But F is in another far remote city. In that case, Is that possible for me to choose a policy, in which the record will be replicated in two cities first and the write will return successfully,  then the record will also be replicated to the third city later?

**Comment by MohamedBassem** [comment]
As of now, this is not possible unfortunately. LogDevice currently only supports synchronous replication and only responds to the clients when all the copies have been successfully persisted.

**Comment by xuning97** [comment]
I heard there is some kind of role like learner in paxos, maybe it's possible to add such a role to copyset.

**Comment by tau0** [comment]
Hi @xuning97,
we were thinking before how to achieve this internally and here are some thoughts. But before jumping to potential solutions let me describe briefly why it is difficult to achieve it with the current design. 

The answer is copysets. The copyset is persisted alongside with every record and used in our read-path and rebuilding to pick the node responsible for data delivery. So here comes the concept of waves. If we failed at least one STORE operation to storages (1 out of 3) and want to replace one node to another we'll need to re-replicate all 3 stores otherwise copyset will be inconsistent and will complicate the selection of the node who will deliver data later on read path. The attempt to replicate to 3 nodes is called a "wave". And in the next "waves" we will need to do everything from scratch.

Potential solutions:
1) The one is actually add async copy to the copyset on the same terms as the rest and allow silent-underreplication (e.g if we cannot replicated data asynchronously to that node - give up). Sadly it makes the reasoning about consistency of the system really hard. The question is mostly about when to declare data loss. And we are trying to improve complexity of LogDevice and prioritizing projects about simplicity. I believe somewhat similar concept was already implemented in LogDevice and was called "extra copies".

2) The other approach is to completely retire copysets. It gives us a lot of flexibility and potentially even simplicity. We will be able to eliminate the concept of waves on the write path and simplify rebuilding. The cost is that it requires a completely different read-path, which will be relying on getting a digest of records from servers before actually requesting records. The current read-path relies on copysets to do server side filtering and pick a leader/sender to achieve single copy delivery of the record.

**Comment by xuning97** [comment]
Hi @tau0 ,
The first of the potential solutions seems possible.
If there're special member in the copyset, like a learner member, it's recorded as part of the copyset, and the background logic might try to replicate the record the it asynchronously. That's all, for other logic, like consistency reasoning, we may still follow previous logic. 
Based on my shallow understanding, “extra copies” is designed to improve the success rate of one wave, it's not to be copied asynchronously.
The background behind my question is to provide one extra level of protection, in case the DCs in the same city are all destroyed, we may get some data back from another city (just to have a little chance)
