### ISSUE TITLE
Find boost-python reliably cross linux distributions

### ISSUE THREAD

**Issue by skindstrom** [facebookincubator/LogDevice#35]
This issue breaks out the second point from #31 into a separate issue.

**The below text is copied from the original issue**
The `_boost_py_component` is not correctly set when building on Fedora, causing boost-python to not be found. I was able to make it work by setting `_boost_py_component` to `python3`, but that's obviously not an acceptable solution for all distros. Not sure how to solve this one, I remember hearing something about the struggles with this versioning last summer. [There seems to be a solution for boost python libs merged into CMake 3.11](https://gitlab.kitware.com/cmake/cmake/merge_requests/1865), but I didn't look into it too deeply.

Error message when not finding the correct boost python version.
```
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1879 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_python-py35

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMake/logdevice-deps.cmake:16 (find_package)
  CMakeLists.txt:34 (include)
```

**Comment by SimonKinds** [comment]
While playing around with the Fedora docker containers I noticed that setting `_boost_py_component` to `python3` works in the Ubuntu container as well! In both Fedora and Ubuntu (and Arch), `libboost_python3` is symlinked to the file using the distro custom versioning scheme. Because of this, it can be detected when `_boost_py_component` is `python3`. 

However, this may cause issues when a specific python version is needed, and I believe logdevice specifically requires python 3.6 (because of `nubia` https://github.com/facebookincubator/python-nubia/issues/2). If the main goal is to simply get the containers working, I would suggest setting the `_boost_py_component` to `python3` and be done with it, as they are using python 3.6.

If 3.7 support is achieved in `nubia`, I see no drawbacks to setting `_boost_py_component` to `python3`, as a check for a minimum python version is made here (which should be updated to 3.6) https://github.com/facebookincubator/LogDevice/blob/2c0d9d5d9a38dfc5e60886acabc0a036eb43031e/logdevice/CMake/logdevice-deps.cmake#L8

Let me know your thoughts and I'll send a PR your way.

**Comment by calebmarchent** [comment]
Sorry that its taken a while to get to this one, the python3 is good, except for on Ubuntu Xenial, a platform for which I still need LogDevice to be able to build. I had a good look around the internet to see if any reliable solutions existed and I finally conclude that they simply don't; I understand there is an aspiration to "re-vamp" the FindBoost logic; but of course that would only be deployed into newer distribution versions. 

Re-writing (including) a customised version of the FindBoost.cmake file, might be an options, but there is a lot of logic there that would end up with maintaining divergent logic. This leaves us with trying the different expected combinations, until one works; using a CMake foreach() loop or the like?

Please let me know your thoughts?

**Comment by calebmarchent** [comment]
Fixed by: https://github.com/facebookincubator/LogDevice/pull/55
where we first try python3, if that fails, retry with python-py35, which catches the Ubuntu 16.04 case.
