### ISSUE TITLE
Question: is it possible to read inconsistent data?

### ISSUE THREAD

**Issue by TennyZhuang** [facebookincubator/LogDevice#79]
I read the docs/API introduction, overview, concepts and Terminology, and have some questions about the design.

The append request will be sent to multiple storage server.

> LogDevice achieves durability by storing several identical copies of each record (typically two or three) on different machines.

What happened if the client panic and the first replica of record flushed but the second lost?(1) There will be an unacknowledged record with only one replica in the cluster. And if another client read the log with mode SCD from LSN_OLDEST now, is it possible that it got the unacknowledged record?(2) or client should read at least 2 same replicas of a record before return the result?(3) then How to distinguish between two records that the first is an unacknowledged dirty record with 1 replica and the second is an acknowledged record with 2 replicas but 1 crashed?(4)

**Comment by mzbeck** [comment]
Hi, the application that's writing only gets an acknowledgement that the record was written if it was stored by the number of nodes configured in the replication factor for the log. So if you said the record has to be replicated 3 times, 3 nodes have to say they stored it. Otherwise your application does not get an ack. Also, those records are not released for reading until those nodes have stored the record. So the storage nodes doesn't send the client reader unacknowledged records.

If something goes wrong and not all 3 copies are available at read time, the client reader (not your application) will figure out what to do. For example, if it's reading in SCD mode and doesn't get the record it expected, then it'll switch out of SCD mode. 

We are working on more documentation about these topics, but feel free to ask questions.

**Comment by TennyZhuang** [comment]
Thanks for your reply.

> Otherwise your application does not get an ack. Also, those records are not released for reading until those nodes have stored the record.

Is there some consistency algorithm to ensure the record is really committed and safe to release between the 3 replicas? Such as 2PC/3PC or more strict Paxos or Raft?

**Comment by runemaster** [comment]
> Is there some consistency algorithm to ensure the record is really committed and safe to release between the 3 replicas? Such as 2PC/3PC or more strict Paxos or Raft?

IMO the implementation can be considered as a variant of Multi-Paxos: the steady state replication in LogDevice can be considered as Phase 2 of Paxos. During sequencer fail-over, LogDevice performs a log recovery procedure in which the successor sequencer(s) execute both Phase 1 and Phase 2 to "seal" a quorum of the previous epoch and reach consensus on the final state of the previous epoch replicated on the storage nodes. Those dirty records at the end of the previous epoch during sequence failure won't get released until the whole log recovery procedure is done.
