### ISSUE TITLE
Is LogDevice Production ready?

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [facebookincubator/LogDevice#98]
Is LogDevice Production ready? Why no release version?

**Comment by MohamedBassem** [comment]
LogDevice is being used in production at facebook for multiple years now serving more than a terabyte per second of total throughput for some usecases. You can check this talk about some of its production usecases at facebook: [link](https://atscaleconference.com/videos/logdevice-a-file-structured-log-system/).
In the OSS world, The implementation for some of the plugins are missing (most importantly: stats publishing & tracer plugins) and some of the tooling that we use internally are still not open source (nothing critical though). We're working on addressing that, for example, I'm slowly building a [prometheus plugin for logdevice](https://github.com/MohamedBassem/logdevice-prometheus) that's still WIP, also other team members are implementing a new tooling framework (we call it LDops 2.0) that among with a lot of other stuff, will allow us to open source more and more tools. So TL;DR although LogDevice is fully functioning and usable in OSS, you may be missing some observability on the system because of the missing implementation for some of the plugins.
As for the release version, I'll be cutting a stable release version in the next couple of weeks mirroring one of our internal releases.

**Comment by zhengxiaochuan-3** [comment]
Thanks a lot. I`m using LogDevice about 3 weeks and it runs very well. Great project, Looking forward to the release version!
BTW, I am writing a LogFS (use libfuse and LogDevice), for a normal user to write a normal log with posix interface.

**Comment by MohamedBassem** [comment]
I'm glad to hear that! Let us know if you face any issue. We also have a [facebook group](https://www.facebook.com/groups/logdevice.oss/) that you can post questions to and we will happily answer them.

Btw, I'm interested in your setup if you're ok with sharing. Are you using a local cluster (using the ld-dev-cluster tool), or is it deployed somewhere?

**Comment by zhengxiaochuan-3** [comment]
Zookeeper servers: 5
LD servers: 12 for now
Deployed with docker, per server a container
More than 500MB/s of total throughput for now
Will do some destructive testing, stop one container when R/W, for example.

**Comment by MohamedBassem** [comment]
Nice! Thanks for sharing :)
Btw, later this year, we will be landing a project called “Node Self Registration” which will get rid of the hardcoded IPs, and allow smoother integration with kubernetes which will make deploying a logdevice cluster with docker way easier.

**Comment by zhengxiaochuan-3** [comment]
Let`s go!    :)
Maybe I can help to write a kubernetes operator for LogDevice for future.
And, I will push LogFS that I mentioned to libfuse [list](https://github.com/libfuse/libfuse/wiki/Filesystems)

**Comment by MohamedBassem** [comment]
Awesome!
I’ll close the issue for now. Let us know if you have further questions.
